version = 0.1
[DBA-PowerShell-Lambda.deploy.parameters]
stack_name = "DBA-PowerShell-Lambda"
resolve_s3 = false
s3_prefix = "DBA-PowerShell-Lambda"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.deploy.parameters]
stack_name = "DBA-PowerShell-Lambda"
resolve_s3 = true
s3_prefix = "DBA-PowerShell-Lambda"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
