version = 0.1
[default.deploy.parameters]
stack_name = "PowerShell-Lambda-V2"
resolve_s3 = true
s3_prefix = "PowerShell-Lambda-V2"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
