AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PowerShell custom runtime and a Lambda function.
##########################################################################
#  Parameters & Globals                                                  #
##########################################################################
Globals:
  Function:
    Tracing: Active
    Tags:
      Application: runtime-layer-function
Resources:
##########################################################################
#  Lambda functions                                                      #
##########################################################################
  PowerShellFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      Description: PowerShell-Lambda-Runtime Function
      CodeUri: function/
      Runtime: provided.al2
      Handler: handlerScript.ps1::handler
      MemorySize: 512
      Timeout: 100
      Layers:
        - !Ref PowerShellRuntime
        - !Ref PowerShellModules
    Metadata:
      BuildMethod: makefile
##########################################################################
#  Lambda layers                                                         #
##########################################################################
  PowerShellRuntime:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Lambda Layer containing PowerShell
      ContentUri: ./layers/runtimeLayer
      CompatibleRuntimes:
        - provided.al2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  PwshRuntimeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: lambda-powershell-runtime-latest-version-arn
      Description: PwshRuntime Layer Name
      Type: String
      Value: !Ref PowerShellRuntime

  PowerShellModules:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer containing PowerShell Modules
      ContentUri: ./layers/modulesLayer
      CompatibleRuntimes:
        - provided.al2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  AWSToolsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: lambda-powershell-latest-version-arn
      Description: PowerShell Modules Layer Name
      Type: String
      Value: !Ref PowerShellModules

##########################################################################
#  OUTPUTS                                                               #
##########################################################################
Outputs:
  PowerShellRuntime:
    Value: !Ref PowerShellRuntime
    Description: PowerShellRuntime Layer ARN
  PowerShellModules:
    Value: !Ref PowerShellModules
    Description: PowerShellModules Layer ARN
  PowerShellFunction:
    Value: !Ref PowerShellFunction
    Description: PowerShell Lambda Function












