AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PowerShell custom runtime and a Lambda function.
##########################################################################
#  Parameters & Globals                                                  #
##########################################################################
Globals:
  Function:
    Tracing: Active
    Tags:
      Application: runtime-layer-function
Resources:
##########################################################################
#  Lambda functions                                                      #
##########################################################################
  PowerShellFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      Description: PowerShell-Lambda-Runtime Function
      CodeUri: function/
      Runtime: provided.al2
      Handler: examplehandler.ps1::handler
      MemorySize: 512
      Timeout: 100
      Layers:
        - !Ref PwshRuntimeLayer
        - !Ref AWSToolsLayer
    Metadata:
      BuildMethod: makefile
##########################################################################
#  Lambda layers                                                         #
##########################################################################
  PwshRuntimeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Lambda Layer containing PowerShell
      ContentUri: ./layers/runtimeLayer
      CompatibleRuntimes:
        - provided.al2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  PwshRuntimeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: lambda-powershell-runtime-latest-version-arn
      Description: PwshRuntime Layer Name
      Type: String
      Value: !Ref PwshRuntimeLayer

  AWSToolsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer containing AWS.Tools
      ContentUri: ./layers/modulesLayer
      CompatibleRuntimes:
        - provided.al2
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  AWSToolsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: lambda-powershell-AWSTools-latest-version-arn
      Description: AWSTools Layer Name
      Type: String
      Value: !Ref AWSToolsLayer

##########################################################################
#  OUTPUTS                                                               #
##########################################################################
Outputs:
  PwshRuntimeLayer:
    Value: !Ref PwshRuntimeLayer
    Description: PwshRuntimeLayer Layer ARN
  AWSToolsLayer:
    Value: !Ref AWSToolsLayer
    Description: AWSToolsLayer Layer ARN
  PowerShellFunction:
    Value: !Ref PowerShellFunction
    Description: PowerShell Lambda Function















